---
- name: install java and net-tools
  hosts: 54.145.31.96
  become: yes
  tasks: 
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install java version 8
      apt: 
        name=openjdk-8-jre-headless
    - name: Install net-tools
      apt:
        name=net-tools

- name: Download and unpack nexus installer
  hosts: 54.145.31.96
  become: yes
  tasks:
    - name: Download Nexus
      get_url: # module to download files from the internet (from http, https or ftp servers) to the remote server. Just like using wget for windows targets, it is "win_get_url"
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/