---
- name: Install Java, net-tools, and Nexus
  hosts: nexus_server
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install Java version 8
      apt:
        name: openjdk-8-jre-headless

    - name: Install net-tools
      apt:
        name: net-tools

- name: Download nexus, Untar and Find folder
  hosts: nexus_server
  become: yes
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      notify: Untar Nexus installer
      register: download_result
    #- debug: msg={{download_result}}

  #handlers:
    - name: Untar Nexus installer
      unarchive:
        src: "{{download_result.dest}}"      #/opt/nexus-3.61.0-02-unix.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Find nexus folder
      find: #find module, which returns a list of files based on specific criteria
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_result # use the register module to declare a variable to print out the result using the debug task
    #- debug: msg={{find_result}} #print the result of the find nexus folder task.
    
    - name: Check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}  #check if the /opt/nexus directory exists
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}}  /opt/nexus
      when: not stat_result.stat.exists

- name: Create Nexus User to own nexus folders
  hosts: nexus_server
  become: yes
  tasks:
    - name: Create Nexus group
      group:
        name: nexus
        state: present
    - name: Create Nexus User
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start Nexus with nexus user
  hosts: nexus_server
  become: yes
  tasks:
    - name: Set the default user to run as nexus user
      # blockinfile:
      #   path: /opt/nexus/bin/nexus.rc
      #   block: | # the pipe symbol represents a multi-line string
      #     run_as_user="nexus"
      lineinfile:      #use lineinfile module instead of blockinfile
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start Nexus
      command: /opt/nexus/bin/nexus start

- name: Verify if nexus is running
  hosts: nexus_server
  tasks:
    - name: Check if nexus is running with ps command
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: wait for a minute
      pause: #use the pause module to wait for a minute
        minutes: 1
    - name: check with netsat
      shell: netstat -tunlp
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
